server:
  port: 8666
spring:
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///blog?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
  jackson:
    time-zone: GMT+8
